### ISSUE TITLE
newer peewee versions remove 'case'

### ISSUE THREAD

**Issue by aerickson** [croscon/fleaker#50]
https://github.com/coleifer/peewee/blob/master/playhouse/shortcuts.py

```
Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
    self.load_wsgi()
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
    __import__(module)
  File "/app/inqqqq/main.py", line 11, in <module>
    from inqqqq.auth import *
  File "/app/inqqqq/auth.py", line 11, in <module>
    from inqqqq import models
  File "/app/inqqqq/models.py", line 4, in <module>
    from fleaker.peewee import PendulumDateTimeField
  File "/app/.heroku/python/lib/python3.6/site-packages/fleaker/peewee/__init__.py", line 26, in <module>
    from .mixins import (
  File "/app/.heroku/python/lib/python3.6/site-packages/fleaker/peewee/mixins/__init__.py", line 8, in <module>
    from .search import SearchMixin
  File "/app/.heroku/python/lib/python3.6/site-packages/fleaker/peewee/mixins/search.py", line 75, in <module>
    from playhouse.shortcuts import case
ImportError: cannot import name 'case'
```

**Comment by aerickson** [comment]
Ah, looks like it's been moved to core peewee. 

https://github.com/coleifer/peewee/commit/54a672547f549eb381cd9578a2b19310bcf5ef1d#diff-fb91356644dedd101277b87ea422e488

**Comment by aerickson** [comment]
List of other changes in Peewee 3.0.

http://docs.peewee-orm.com/en/latest/peewee/changes.html
